name: flutter_test_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  hive: 
  hive_flutter:
  provider: any
  http:
  firebase_core: ^3.10.1
  firebase_auth: ^5.3.4
  go_router: 
  cloud_firestore: ^5.6.3
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: 
  build_runner: 
  mockito: ^5.4.2


flutter:
  uses-material-design: true
