// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxS6lMGpaUO_xU8WEQpxA8ef0OE2zymkY',
    appId: '1:430171387813:ios:c6912c2883dbe0b9ba9a4c',
    messagingSenderId: '430171387813',
    projectId: 'vepart-app',
    storageBucket: 'vepart-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiKyukAyk_sxb0UBUy-vGiG_6Aoh2kzyE',
    appId: '1:430171387813:web:65b5a1516bfe83e1ba9a4c',
    messagingSenderId: '430171387813',
    projectId: 'vepart-app',
    authDomain: 'vepart-app.firebaseapp.com',
    storageBucket: 'vepart-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxS6lMGpaUO_xU8WEQpxA8ef0OE2zymkY',
    appId: '1:430171387813:ios:c6912c2883dbe0b9ba9a4c',
    messagingSenderId: '430171387813',
    projectId: 'vepart-app',
    storageBucket: 'vepart-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9KzAxxHXqe6rD37uZ2XA3BncqK7tNtXI',
    appId: '1:430171387813:android:1daa8f101e9972ffba9a4c',
    messagingSenderId: '430171387813',
    projectId: 'vepart-app',
    storageBucket: 'vepart-app.firebasestorage.app',
  );

}